name: xhycom-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - xarray
  - cftime
  - sphinx
  - sphinx-book-theme
  - myst-nb
  - sphinx-copybutton
  - sphinx-design
  - jupyter
  - pip
  - pip:
      - -e ..         # install xhycom itself in editable mode
